PROGRAM READDATA
	IMPLICIT NONE
	INTEGER :: N,i,S=0
	INTEGER,ALLOCATABLE :: d(:,:)
	OPEN(UNIT=10,FILE="D:\data.dat",STATUS='OLD',ACCESS='SEQUENTIAL')
	N=-1
	DO WHILE(.TRUE.)
		WRITE(*,*)"INPUT A INTEGER:"
		READ(*,*)N
		IF(N<=0) THEN
			WRITE(*,*)"ERROR,TRY AGAIN!"
		ELSE
			EXIT
		ENDIF
	ENDDO
	ALLOCATE(d(N,2))
	d=0
	DO i=1,N
		READ(UNIT=10,FMT="(2I5.1)",IOSTAT=S)d(i,1),d(i,2)
		IF(d(i,1)==0.OR.d(i,2)==0) THEN
			WRITE(*,"(A27I5/A14)")"THERE MAYBE A ERROR IN LINE",i,"PROGRAM EXIT!!"
			EXIT !若存在没有两个数据的行则退出
		ENDIF
		IF(S/=0) THEN
			WRITE(*,*)"THE END OF THE FILE"
			N=i
			EXIT !若输入行数大于总行数，退出
		ENDIF
	ENDDO
	!输出读入的数据
	WRITE(*,*)"THE DATA READ FROM THE FILE IS:"
	DO i=1,N
		WRITE(*,"(2I5.1)")d(i,1),d(i,2)
	ENDDO
	DEALLOCATE(d)
	CLOSE(10)
END
	