PROGRAM MAIN
	IMPLICIT NONE
	INTEGER :: A(100),i
	OPEN(UNIT=10,FILE="../DATA/OUTPUT1.DAT")
	DO i=1,SIZE(A)
		A(i)=i
	ENDDO
	CALL INIT_RANDOM_SEED()
	CALL FISHER_YATES_SHUFFLE(A,SIZE(A))
	WRITE(10,"(I10)")A
	CLOSE(10)
END	
SUBROUTINE FISHER_YATES_SHUFFLE(A,M)
	IMPLICIT NONE
	INTEGER :: A(*),i,j,TEM,M
	REAL(8) :: RAM
	DO i=M,1,-1
		CALL RANDOM_NUMBER(RAM)
		j=CEILING(RAM*i)
		TEM=A(i)
		A(i)=A(j)
		A(j)=TEM
	ENDDO
END
SUBROUTINE INIT_RANDOM_SEED()
	INTEGER :: i, n, clock
	INTEGER, DIMENSION(:), ALLOCATABLE :: seed
	CALL RANDOM_SEED(size = n)
	ALLOCATE(seed(n))
	CALL SYSTEM_CLOCK(COUNT=clock)
	seed = clock + 37 * (/ (i - 1, i = 1, n) /)
	CALL RANDOM_SEED(PUT = seed)
	DEALLOCATE(seed)
END SUBROUTINE